### PR TITLE
Added GitHub action

### PR DESCRIPTION
**Pull request by rickvdbosch**

### CODE REVIEW

**Comment by jfversluis** [comment]
This still a draft?

**Comment by rickvdbosch** [comment]
As far as I'm concerned: yes. We don't have a published artifact from this workflow yet. If that's not something we expect from this workflow (now), this PR can be set to ready for review.

**Comment by jfversluis** [comment]
All fine by me! Was just wondering what you plan was with this :D

**Comment by rickvdbosch** [comment]
Long story short: having the build that checks the PR be a GitHub action makes it easier to find errors if there are any. 
And GitHub actions 🤓

**Pull request merged**
